### ISSUE TITLE
error when list

### ISSUE THREAD

**Issue by Jadlokin-Scarlet** [Zaitonn/iPanel#12]
```
list
1:57:16 PM Info  当前有1个实例在线
1:57:16 PM Error 解析命令时出现异常
1:57:16 PM Error System.InvalidOperationException: Could not find color or style '::ffff:127.0.0.1'.
1:57:16 PM Error    at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:line 17
1:57:16 PM Error    at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 22
1:57:16 PM Error    at Spectre.Console.Markup..ctor(String text, Style style) in /_/src/Spectre.Console/Widgets/Markup.cs:line 42
1:57:16 PM Error    at Spectre.Console.TableExtensions.<>c.<AddRow>b__6_0(String column) in /_/src/Spectre.Console/Extensions/TableExtensions.cs:line 160
1:57:16 PM Error    at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
1:57:16 PM Error    at Spectre.Console.TableExtensions.AddRow(Table table, String[] columns) in /_/src/Spectre.Console/Extensions/TableExtensions.cs:line 160
1:57:16 PM Error    at iPanel.Core.Interaction.Commands.ListConnectionCommand.Parse(String[] args) in D:\a\iPanel\iPanel\iPanel\Core\Interaction\Commands\ListConnectionCommand.cs:line 33
1:57:16 PM Error    at iPanel.Core.Interaction.InputReader.Handle(List`1 args) in D:\a\iPanel\iPanel\iPanel\Core\Interaction\InputReader.cs:line 166
```

**Comment by Jadlokin-Scarlet** [comment]
run in ubuntu 20.0 with x64 release

**Comment by Zaitonn** [comment]
感谢反馈，预计晚上修复

**Comment by Zaitonn** [comment]
已修复
你可以在[这下载](https://github.com/iPanelDev/iPanel/actions/runs/7518393452)测试版
